module.exports = {
  env: {
    NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
    NEXT_PUBLIC_VERCEL_URL:process.env.NEXT_PUBLIC_VERCEL_URL,
    NEXT_PUBLIC_PROTOCOL:process.env.NEXT_PUBLIC_PROTOCOL,
    NEXT_PUBLIC_FIREBASE_DATABASE_URL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL,
    NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY,
    NEXT_PUBLIC_FIREBASE_PRIVATE_KEY_ID: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY_ID,
    NEXT_PUBLIC_FIREBASE_CLIENT_ID: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_ID,
    NEXT_PUBLIC_AUTH_URI: process.env.NEXT_PUBLIC_AUTH_URI
    
  },
  reactStrictMode: true,
  images: {
    domains: ['via.placeholder.com','media-exp3.licdn.com'],
  },
}