
module.exports = {
  env: {
    NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
    NEXT_PUBLIC_VERCEL_URL: process.env.NEXT_PUBLIC_VERCEL_URL,
    NEXT_PUBLIC_PROTOCOL: process.env.NEXT_PUBLIC_PROTOCOL,
    NEXT_PUBLIC_FIREBASE_DATABASE_URL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL,
    NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY,
    NEXT_PUBLIC_FIREBASE_PRIVATE_KEY_ID: process.env.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY_ID,
    NEXT_PUBLIC_FIREBASE_CLIENT_ID: process.env.NEXT_PUBLIC_FIREBASE_CLIENT_ID,
    NEXT_PUBLIC_AUTH_URI: process.env.NEXT_PUBLIC_AUTH_URI,
    S3_UPLOAD_KEY: process.env.S3_UPLOAD_KEY,
    S3_UPLOAD_SECRET: process.env.S3_UPLOAD_SECRET,
    S3_UPLOAD_REGION: process.env.S3_UPLOAD_REGION,
    S3_UPLOAD_BUCKET: process.env.S3_UPLOAD_BUCKET,
    NEXT_PUBLIC_S3_URL: process.env.NEXT_PUBLIC_S3_URL

  },
  reactStrictMode: true,
  images: {
    domains: ['via.placeholder.com', 'media-exp3.licdn.com'],
  },
}